AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template to deploy API to store and fetch data from OGN

  '
Globals:
  Function:
    Timeout: 20
Resources:
  dataFetchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ognDataFetchFunction
      CodeUri: s3://tc-airspace-data-cf-backend/41de49428772925f82fe308d1cc47f85
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          loMax: 3.6474609375000004
          loMin: -13.710937500000002
          laMax: 59.355596110016315
          laMin: 49.61070993807422
          tableName: flarmData
      Policies:
      - AmazonDynamoDBFullAccess
