AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template to deploy API to store and fetch data from OGN

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: ognDataFetchFunction
      CodeUri: fetchData/
      Handler: app.lambda_handler
      Runtime: python3.7